# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: ''
url: http://blog.thib.me
title: Thibaud’s blog
subtitle: Notes, thoughts, and open-source software
author: Thibaud Colas
authorsite: http://thib.me
# simple_search: http://google.com/search
description: Logbook of a software engineer navigating web development
keywords: thibaud colas thibaudcolas blog software engineer web developer javascript

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
# %F - ISO 8601 %R - time, 24-hour
date_format: "%F %R"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:title
source: source
destination: public
# plugins_dir: plugins
plugins:
  - jekyll-paginate
code_dir: downloads/code
category_dir: categories
markdown: kramdown
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: false # default python pygments have been replaced by pygments.rb

paginate: 5           # Posts per page on the blog index
pagination_dir:       # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
# https://github.com/octopress/filters#excerpted-posts
excerpt_separator: <!-- more -->

titlecase: false       # Converts page and post titles to titlecase


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: thibaudcolas
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: thibaud_colas
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 102675689688248197665
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-34692999-2

# Facebook Like
facebook_like: false